# Generated by Django 5.0.6 on 2024-06-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_doregister_rename_email_login_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
