# Generated by Django 5.0.6 on 2024-06-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Logincheck',
        ),
    ]
