# Generated by Django 5.0.6 on 2024-06-23 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_login_logincheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logincheck',
        ),
    ]
